# Generated by Django 4.2.27 on 2026-06-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Não Iniciado"),
                    ("IN_PROGRESS", "Em Andamento"),
                    ("PAUSED", "Pausado"),
                    ("COMPLETED", "Finalizado"),
                    ("AGUARDANDO_LIDER", "Aguardando Líder"),
                    ("APROVADO", "Aprovado"),
                    ("REPROVADO_LIDER", "Reprovado pelo Líder"),
                    ("REPROVAR_FINAL_REFAZER", "Reprovado Final - Refazer"),
                ],
                default="NOT_STARTED",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="checklisttimelinelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("START", "Iniciar"),
                    ("PAUSE", "Pausar"),
                    ("CONTINUE", "Continuar"),
                    ("FINISH", "Finalizar"),
                    ("REOPEN", "Reabrir para Ajustes"),
                    ("APPROVE_LIDER", "Aprovar pelo Líder"),
                    ("REJECT_LIDER", "Reprovar pelo Líder"),
                    ("APPROVE_ANALISTA", "Aprovar pelo Analista"),
                    ("REJECT_ANALISTA", "Reprovar pelo Analista"),
                ],
                max_length=20,
                verbose_name="Ação",
            ),
        ),
    ]
