# Generated by Django 4.2.27 on 2026-06-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_checklistsession_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklistsession",
            name="leader_name",
        ),
        migrations.AddField(
            model_name="checklistsession",
            name="leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="led_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Líder de Turno",
            ),
        ),
    ]
