# Generated by Django 4.2.27 on 2026-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_checklistsession_leader_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklisttimelinelog",
            name="pause_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo da Pausa"
            ),
        ),
    ]
