# Generated by Django 4.2.27 on 2026-06-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_checklisttimelinelog_pause_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistsession",
            name="general_observations",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Observações Gerais (Estado da Máquina)",
            ),
        ),
    ]
