# Generated by Django 4.2.27 on 2026-06-23 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_checklistsession_general_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistsession",
            name="co_inspector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="co_inspections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Co-Inspetor",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="partner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_of",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Parceiro de Turno",
            ),
        ),
    ]
