# Generated by Django 4.2.27 on 2026-06-30 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_checklistsession_co_inspector_user_partner_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitemvalue",
            name="auditor_is_divergent",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Divergente?"
            ),
        ),
        migrations.AddField(
            model_name="checklistitemvalue",
            name="auditor_observation",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observação do Auditor"
            ),
        ),
        migrations.AddField(
            model_name="checklistsession",
            name="audit_status",
            field=models.CharField(
                choices=[
                    ("NAO_AUDITADO", "Não Auditado"),
                    ("AUDITADO_CONFORME", "Auditado - Conforme"),
                    ("AUDITADO_COM_DIVERGENCIA", "Auditado - Com Divergência"),
                ],
                default="NAO_AUDITADO",
                max_length=30,
                verbose_name="Status da Auditoria",
            ),
        ),
        migrations.AddField(
            model_name="checklistsession",
            name="audited_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Auditado em"
            ),
        ),
        migrations.AddField(
            model_name="checklistsession",
            name="audited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audited_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auditado por",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Eletricista", "Eletricista"),
                    ("Mecânico", "Mecânico"),
                    ("Eletromecânico", "Eletromecânico"),
                    ("Analista", "Analista"),
                    ("Diretor", "Diretor"),
                    ("Lider", "Lider"),
                    ("Auditor", "Auditor"),
                ],
                max_length=50,
                verbose_name="Especialidade",
            ),
        ),
    ]
